<?php
require __DIR__.'/../includes/functions.php'; require_staff();
$id=(int)($_GET['id']??0);
$q=db()->prepare("SELECT u.*,p.* FROM users u LEFT JOIN student_profiles p ON p.user_id=u.id WHERE u.id=? AND u.role='student'"); $q->execute([$id]); $s=$q->fetch(); if(!$s) redirect('/admin/index.php');
audit('view','student',$id,user()['role']);
if($_SERVER['REQUEST_METHOD']==='POST'){
 check_csrf();
 if(isset($_POST['body'])){ $b=trim($_POST['body']??''); if($b){$cats=['general','education','counseling','health','family','urgent'];$cat=$_POST['category']??'general';if(!in_array($cat,$cats,true))$cat='general';db()->prepare("INSERT INTO messages(student_id,sender_role,body,category,is_urgent) VALUES(?, 'admin', ?, ?, ?)")->execute([$id,$b,$cat,$cat==='urgent'?1:0]);audit('message_sent','student',$id,$cat);} flash('پیام ارسال شد.'); }
 elseif(isset($_POST['internal_note'])){ if(user()['role'] !== 'admin'){ http_response_code(403); exit('دسترسی ثبت یادداشت داخلی فقط برای مدیر است.'); } $b=trim($_POST['internal_note']??''); if($b) db()->prepare('INSERT INTO admin_notes(student_id,admin_id,body) VALUES(?,?,?)')->execute([$id,user()['id'],$b]); audit('note_created','student',$id); flash('یادداشت داخلی ثبت شد.'); }
 elseif(isset($_POST['save_followup'])){ if(user()['role'] !== 'admin'){ http_response_code(403); exit('دسترسی پیگیری فقط برای مدیر است.'); } $allowed=['new','in_progress','referred','done','closed']; $st=$_POST['case_status']??'new'; if(!in_array($st,$allowed,true))$st='new'; db()->prepare('UPDATE student_profiles SET case_status=?,followup_note=?,next_followup_date=?,last_followup_at=NOW() WHERE user_id=?')->execute([$st,trim($_POST['followup_note']??''),($_POST['next_followup_date']??'')?:null,$id]); audit('followup_updated','student',$id,$st); flash('اطلاعات پیگیری ذخیره شد.'); }
 redirect('/admin/student.php?id='.$id);
}
db()->prepare("UPDATE messages SET is_read=1 WHERE student_id=? AND sender_role='student'")->execute([$id]);
$m=db()->prepare('SELECT * FROM messages WHERE student_id=? ORDER BY created_at DESC');$m->execute([$id]);
$n=db()->prepare('SELECT n.*,u.name AS admin_name FROM admin_notes n JOIN users u ON u.id=n.admin_id WHERE n.student_id=? ORDER BY n.created_at DESC');$n->execute([$id]);
$labels=['new'=>'جدید','in_progress'=>'در حال پیگیری','referred'=>'ارجاع‌شده','done'=>'انجام‌شده','closed'=>'بسته‌شده'];
layout_start('پرونده دانش‌آموز'); ?>
<a href="<?=e(url('/admin/index.php'))?>">← بازگشت به فهرست</a><div class="page-head"><div><p class="eyebrow">پرونده محرمانه</p><h1><?=e($s['name'])?></h1></div><?php if($s['emergency_flag']):?><span class="badge danger">نیازمند ارجاع/پیگیری</span><?php endif;?></div>
<div class="details card"><div><b>موبایل:</b> <?=e($s['mobile'])?></div><div><b>پایه / رشته:</b> <?=e($s['grade']??'—')?> / <?=e($s['study_field']??'—')?></div><?php if(can_view_sensitive()):?><div><b>کد ملی:</b> <?=e($s['national_id']??'—')?></div><?php endif;?><div><b>تولد:</b> <?=e($s['birth_date']??'—')?></div><div><b>والد:</b> <?=e($s['parent_name']??'—')?><?php if(can_view_sensitive()):?> / <?=e($s['parent_phone']??'—')?><?php endif;?></div><?php if(can_view_sensitive()):?><div><b>تماس اضطراری:</b> <?=e($s['emergency_contact']??'—')?> / <?=e($s['emergency_phone']??'—')?></div><?php endif;?><div><b>نقاط قوت:</b> <?=nl2br(e($s['strengths']??'—'))?></div><div><b>درس‌های نیازمند کمک:</b> <?=nl2br(e($s['difficult_subjects']??'—'))?></div><div><b>هدف تحصیلی:</b> <?=nl2br(e($s['academic_goal']??'—'))?></div><div><b>علایق:</b> <?=nl2br(e($s['interests']??'—'))?></div><div><b>حال عمومی:</b> <?=e($s['current_mood']??'—')?></div><div><b>درخواست حمایت:</b> <?=e($s['support_request']??'—')?></div><?php if(can_view_sensitive()):?><div><b>وضعیت خانوادگی:</b> <?=e($s['household_status']??'—')?></div><div><b>حساسیت‌ها:</b> <?=nl2br(e($s['allergies']??'—'))?></div><div><b>نکات سلامت:</b> <?=nl2br(e($s['health_notes']??'—'))?></div><?php endif;?><div class="full"><b>یادداشت دانش‌آموز:</b> <?=nl2br(e($s['student_note']??'—'))?></div></div>
<?php if(user()['role']==='admin'):?><div class="card"><h2>پیگیری پرونده</h2><form class="form-grid" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><label>وضعیت<select name="case_status"><?php foreach($labels as $k=>$v):?><option value="<?=e($k)?>" <?=($s['case_status']??'new')===$k?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label><label>تاریخ پیگیری بعدی<input type="date" name="next_followup_date" value="<?=e($s['next_followup_date']??'')?>"></label><label class="full">یادداشت پیگیری<textarea name="followup_note"><?=e($s['followup_note']??'')?></textarea></label><button class="button" name="save_followup" value="1">ذخیره پیگیری</button></form></div><div class="card"><h2>یادداشت‌های داخلی مدیر</h2><p class="muted">این یادداشت‌ها برای دانش‌آموز نمایش داده نمی‌شوند.</p><?php while($x=$n->fetch()):?><article class="message admin"><small><?=e($x['admin_name'])?> · <?=e($x['created_at'])?></small><p><?=nl2br(e($x['body']))?></p></article><?php endwhile;?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><label>یادداشت جدید<textarea name="internal_note" required></textarea></label><button class="button">ثبت یادداشت داخلی</button></form></div><?php endif;?><div class="card"><h2>پیام‌ها</h2><?php while($x=$m->fetch()):?><article class="message <?=e($x['sender_role'])?>"><small><?=e($x['sender_role']==='admin'?'مدیر':'دانش‌آموز')?> · <?=e($x['created_at'])?> · <?=e($x['category']??'عمومی')?></small><p><?=nl2br(e($x['body']))?></p></article><?php endwhile;?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><label>موضوع پیام<select name="category"><option value="general">عمومی</option><option value="education">آموزشی</option><option value="counseling">مشاوره‌ای</option><option value="health">سلامت</option><option value="family">خانوادگی</option><option value="urgent">نیازمند توجه سریع</option></select></label><label>پیام جدید<textarea name="body" required></textarea></label><button class="button">ارسال پیام</button></form></div><?php layout_end(); ?>
